PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/PrintMedia__c.object-meta.xml
<CustomObject>
    <description>The physical customized materials and parameters used to create the products used in the services offered</description>
    <label>Print Media</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Media number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Print Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Will this be printed in color?</inlineHelpText>
    <label>Print Color</label>
    <type>Checkbox</type>
</CustomField>

PrintShop/orderForm/main/default/classes/orderHandler.cls
public class orderHandler {
    public orderHandler(){

    }

    public static void createNewPrintMedia(List<Order> listOfOrders){

        List<SObject> printMediaList = new List<SObject>();

        for(Order currOrd : listOfOrders){

            PrintMedia__c printM1 = new PrintMedia__c();

            printM1.Color__c=true;

             printMediaList.add(printM1);

        }
        
        insert printMediaList;

    }
}