PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/PrintMedia__c.object-meta.xml
<CustomObject>
    <description>The physical customized materials and parameters used to create the products used in the services offered</description>
    <label>Print Media</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Media number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Print Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/BindingStyle__c.field-meta.xml
<CustomField>
    <fullName>BindingStyle__c</fullName>
    <label>Binding Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loose-Leaf</fullName>
            </value>
            <value>
                <fullName>Perfect</fullName>
            </value>
            <value>
                <fullName>Sprial</fullName>
            </value>
            <value>
                <fullName>Comb</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Case-Bound</fullName>
            </value>
            <value>
                <fullName>Saddle Stitch</fullName>
            </value>
            <value>
                <fullName>Stapled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PrintShop/ListMedia/main/default/classes/TestPrintMediaController.cls
@isTest 
public class TestMediaController {
    @TestSetup
    public static void SetupControllerTests(){
        List<PrintMedia__c> printMediaToInsert = new List<PrintMedia__c>();
        for(Integer i = 0; i <5; i++ ) {
            printMediaToInsert.add(new PrintMedia__c(BindingStyle__c = 'Perfect'));
        }

        insert printMediaToInsert;
    }

    @isTest
    public static void TestCreatePrintMediaWithOneRecord(){
        PrintMedia__c print = [SELECT Id FROM PrintMedia__c WHERE BindingStyle__c ='Perfect' LIMIT 1];

        Test.startTest();
        List<PrintMedia__c> print1 = New List<PrintMedia__c>();
        for (PrintMedia__c p : [SELECT Id FROM PrintMedia__c WHERE BindingStyle__c='Perfect']) {
            print1.add(p.Id);
        }

        System.assertEquals(print1.size() = 1 , print1.size());

        Test.stopTest();
    }
}