PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/PrintMedia__c.object-meta.xml
<CustomObject>
    <description>The physical customized materials and parameters used to create the products used in the services offered</description>
    <label>Print Media</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Media number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Print Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/Customization_Costs__c.field-meta.xml
<CustomField>
    <fullName>Customization_Costs__c</fullName>
    <label>Customization Costs</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/PageMaterial__c.field-meta.xml
<CustomField>
    <fullName>PageMaterial__c</fullName>
    <label>Page Material</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20# Bond</fullName>
            </value>
            <value>
                <fullName>50# Offset</fullName>
            </value>
            <value>
                <fullName>60# Offset</fullName>
            </value>
            <value>
                <fullName>70# Offset</fullName>
            </value>
            <value>
                <fullName>80# Gloss</fullName>
            </value>
            <value>
                <fullName>80# Silk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/PageSize__c.field-meta.xml
<CustomField>
    <fullName>PageSize__c</fullName>
    <label>Page Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A0</fullName>
            </value>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PrintShop/ProductFeatures/main/default/classes/PrintMediaHelperTest.cls
@isTest
public class PrintMediaHelperTest {
    
    @isTest
    public static void TP_calculateCosts(){

        PrintMedia__c testMedia = new PrintMedia__c(
            PageSize__c = 'A0',
            PageMaterial__c = '80# Silk'
        );

        Test.startTest();

        Insert testMedia;
        PrintMedia__c insertedMedia = [SELECT Customization_Costs__c FROM PrintMedia__c LIMIT 1];

        Decimal testCost = insertedMedia.Customization_Costs__c;

        System.assertNotEquals(0, testCost);

        Test.stopTest();
    }

    @isTest
    public static void TB_calculateCosts(){

        List<PrintMedia__c> media = new List<PrintMedia__c>();
        
        for(Integer i=0; i<150; i++){
            PrintMedia__c testMedia = new PrintMedia__c(
                PageSize__c = 'A0',
                PageMaterial__c = '80# Silk'
            );
            media.add(testMedia);
        }

        Test.startTest();

        Insert media;

        for(PrintMedia__c test: [SELECT Customization_Costs__c FROM PrintMedia__c]){
            System.assertNotEquals(0, test.Customization_Costs__c);
        }

        Test.stopTest();

    }
}