PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/PrintMedia__c.object-meta.xml
<CustomObject>
    <description>The physical customized materials and parameters used to create the products used in the services offered</description>
    <label>Print Media</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Media number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Print Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Will this be printed in color?</inlineHelpText>
    <label>Print Color</label>
    <type>Checkbox</type>
</CustomField>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/Cover_Jacket__c.field-meta.xml
<CustomField>
    <fullName>Cover_Jacket__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cover Jacket</label>
    <type>Checkbox</type>
</CustomField>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/Customization_Costs__c.field-meta.xml
<CustomField>
    <fullName>Customization_Costs__c</fullName>
    <label>Customization Costs</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PrintShop/PrintShopObjectCustomizations/main/default/objects/PrintMedia__c/fields/PageMaterial__c.field-meta.xml
<CustomField>
    <fullName>PageMaterial__c</fullName>
    <label>Page Material</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20# Bond</fullName>
            </value>
            <value>
                <fullName>50# Offset</fullName>
            </value>
            <value>
                <fullName>60# Offset</fullName>
            </value>
            <value>
                <fullName>70# Offset</fullName>
            </value>
            <value>
                <fullName>80# Gloss</fullName>
            </value>
            <value>
                <fullName>80# Silk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PrintShop/ProductFeatures/main/default/classes/PrintMediaHelper.cls
public with sharing class PrintMediaHelper {
    
    public static void calculateCosts(List<PrintMedia__c> media){

        for(PrintMedia__c pm : media){
            calculateCostPerCopy(pm);
        }

        update media;
    }

    private static void calculateCostPerCopy(PrintMedia__c media){
        // Cost for page size, per page
        // cost for page material, per page
        // cost for color print per page
        // Cost for cover material
        // Cost for cover jacket
        // Cost for binding stlye
        Decimal totalCost = 0;

        totalCost += MaterialCosts.PAGE_COST;

        totalCost += getPageTypeCost(media);

        if(media.Color__c) totalCost += MaterialCosts.COLOR_PAGE_COST;

        if(media.Cover_Jacket__c) totalCost += MaterialCosts.COVER_JACKET_COST;

        media.Customization_Costs__c = totalCost;
    }

    private static Decimal getPageTypeCost(PrintMedia__c media){
        String pageType = media.PageMaterial__c;

        if(pageType.contains('Bond')) return 0;
        if(pageType.contains('Offset')) return MaterialCosts.OFFSET_COST;
        if(pageType.contains('Gloss')) return MaterialCosts.GLOSS_COST;
        if(pageType.contains('Silk')) return MaterialCosts.SILK_COST;

        return 0;
    }
}